package org.blas.baseapp.domain;
// Generated Feb 11, 2013 2:42:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table( name = "post" )
public class Post  implements java.io.Serializable {
    @Id
    @Column(name="id")
    @GeneratedValue
     private Integer id;
    @Column(name="titulo")
     private String titulo;
    @Column(name="posteos")
     private String post;

    public Post() {
    }

    public Post(String titulo, String post) {
       this.titulo = titulo;
       this.post = post;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }




}


